extends Node

# Enum
enum SET {LIGHT, MEDIUM, HARD}
enum TEA {ASSAM, CEYLON, CHAI, EARL_GREY, HOJICHA, JASMINE, MINT, SENCHA, OOLONG, MATCHA, TARO, WATER, EMPTY}
enum CROP {SUGAR_CANE, CASSAVA, TARO, STRAWBERRY}
enum BOOKS {BOBA_HISTORY, CASSAVA_PROCESS, CULT_DOCTRINE, CULT_FLYER, DEBT, WILL, GONGFU, HOSPICE, MYTH, OLD_LETTER, UNYIELDY, LETTER1, LETTER2, LETTER3, LETTER4, LETTER5, LETTER6, LETTER7, LETTER8, LETTER9, LETTER10, LETTER11, GRANDPA}

# General
const NUMBER_OF_TEAS := 11
const NUMBER_OF_BOOKS := 23
const NUMBER_OF_CROPS := 4

const LIGHT_MONEY := 60000
const LIGHT_TIP := 500
const LIGHT_PRICE := 600
const LIGHT_SEED := 50
const LIGHT_DISAPPOINT := 3
const LIGHT_NEGLECT := 5
const LIGHT_FORGET := 1

const MEDIUM_MONEY := 200
const MEDIUM_TIP := 400
const MEDIUM_PRICE := 500
const MEDIUM_SEED := 50
const MEDIUM_DISAPPOINT := 5
const MEDIUM_NEGLECT := 3
const MEDIUM_FORGET := 1

const HARD_MONEY := 75
const HARD_TIP := 300
const HARD_PRICE := 300
const HARD_SEED := 20
const HARD_DISAPPOINT := 8
const HARD_NEGLECT := 5
const HARD_FORGET := 3
