extends Node

# Enum
enum TEA {ASSAM, CEYLON, CHAI, EARL_GREY, HOJICHA, JASMINE, MINT, SENCHA, OOLONG, MATCHA, TARO, WATER, EMPTY}
enum SET {LIGHT, MEDIUM, HARD}
enum CROP {SUGAR_CANE, CASSAVA, TARO, STRAWBERRY}
enum BOOKS {BOBA_HISTORY, CASSAVA_PROCESS, MYTH, UNYIELDY, GONGFU, CULT_FLYER, CULT_DOCTRINE, OLD_LETTER, LETTER1, LETTER2, LETTER3, LETTER4, LETTER5, LETTER6, LETTER7, LETTER8, LETTER9, LETTER10, LETTER11}

# General
const NUMBER_OF_TEAS := 11
const NUMBER_OF_BOOKS := 8
const NUMBER_OF_CROPS := 4

# Peaceful mode settings
const PEACEFUL_DISAPPOINT := 0
const PEACEFUL_NEGLECT := 0
const PEACEFUL_FORGET := 0
# Story mode settings
const STORY_DISAPPOINT := 5
const STORY_NEGLECT := 3
const STORY_FORGET := 1
# Danger mode settings
const DANGER_DISAPPOINT := 8
const DANGER_NEGLECT := 5
const DANGER_FORGET := 3

# Easy mode settings
const EASY_MONEY := 50
const EASY_TIP := 300
const EASY_PRICE := 500
const EASY_SEED := 10
# Normal mode settings
const NORMAL_MONEY := 75
const NORMAL_TIP := 400
const NORMAL_PRICE := 400
const NORMAL_SEED := 25

# Hard mode settings
const HARD_MONEY := 1000
const HARD_TIP := 500
const HARD_PRICE := 300
const HARD_SEED := 50
